"""modify Organization models

Revision ID: 388ce9073b63
Revises: e8ceeed51666
Create Date: 2024-10-29 11:59:06.561091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388ce9073b63'
down_revision: Union[str, None] = 'e8ceeed51666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('organizations', 'owner_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('organizations', 'owner_contact_no',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('organizations', 'owner_email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'owner_email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('organizations', 'owner_contact_no',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('organizations', 'owner_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
