"""againmodify Organization models

Revision ID: a495dc7ddb4b
Revises: 388ce9073b63
Create Date: 2024-10-29 12:04:58.758158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a495dc7ddb4b'
down_revision: Union[str, None] = '388ce9073b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_by', sa.Integer(), nullable=False))
    op.drop_constraint('organizations_creared_by_fkey', 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'])
    op.drop_column('organizations', 'creared_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('creared_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key('organizations_creared_by_fkey', 'organizations', 'users', ['creared_by'], ['id'])
    op.drop_column('organizations', 'created_by')
    # ### end Alembic commands ###
