"""modify tenantSubscription

Revision ID: 9d165163920e
Revises: 788d6980b917
Create Date: 2024-11-05 12:54:01.976529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d165163920e'
down_revision: Union[str, None] = '788d6980b917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_subscriptions', sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_subscriptions', 'total_amount')
    # ### end Alembic commands ###
